"""
SERVICE_NAME: _ProjectForgeMS
ENTRY_POINT: _ProjectForgeMS.py
DEPENDENCIES: None
"""
import os
import shutil
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional

from microservice_std_lib import service_metadata, service_endpoint

logger = logging.getLogger("ProjectForge")

@service_metadata(
    name="ProjectForge",
    version="1.0.0",
    description="Scaffolding engine for creating new microservice projects or Python apps.",
    tags=["scaffolding", "generator", "filesystem"],
    capabilities=["filesystem:write"]
)
class ProjectForgeMS:
    """
    The Blacksmith.
    Creates directory structures, stamps out boilerplate code, and injects dependencies.
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        # Optional: Define a central template library path
        self.template_root = self.config.get("template_root")

    @service_endpoint(
        inputs={"parent_path": "str", "project_name": "str", "dependencies": "List[str]", "type": "str"},
        outputs={"path": "str", "status": "str"},
        description="Creates a new standardized Python project with the given specifications.",
        tags=["create", "scaffold"],
        side_effects=["filesystem:write"]
    )
    def forge_project(self, 
                      parent_path: str, 
                      project_name: str, 
                      dependencies: List[str] = None, 
                      project_type: str = "microservice") -> Dict[str, Any]:
        """
        Stamps out a new project folder.
        """
        root = Path(parent_path).resolve()
        project_dir = root / project_name
        
        if project_dir.exists():
            raise FileExistsError(f"Directory already exists: {project_dir}")

        logger.info(f"Forging new project '{project_name}' at {project_dir}...")
        
        try:
            # 1. Create Skeleton
            project_dir.mkdir(parents=True)
            (project_dir / "src").mkdir()
            (project_dir / "tests").mkdir()
            (project_dir / "config").mkdir()
            
            # 2. Create Files
            self._create_readme(project_dir, project_name)
            self._create_requirements(project_dir, dependencies or [])
            self._create_gitignore(project_dir)
            
            # 3. Create Entry Point (based on type)
            if project_type == "microservice":
                self._create_microservice_boilerplate(project_dir, project_name)
            else:
                self._create_standard_app_boilerplate(project_dir)

            return {
                "path": str(project_dir),
                "status": "created",
                "name": project_name
            }
            
        except Exception as e:
            # Rollback on failure? Or just log.
            logger.error(f"Forge failed: {e}")
            raise e

    def _create_readme(self, root: Path, name: str):
        content = f"# {name}\n\nGenerated by ProjectForgeMS.\n\n## Overview\nTODO: Add description.\n"
        (root / "README.md").write_text(content, encoding="utf-8")

    def _create_requirements(self, root: Path, deps: List[str]):
        # Always add standard libs if needed
        base_deps = ["requests", "logging"]
        all_deps = sorted(list(set(base_deps + deps)))
        content = "\n".join(all_deps)
        (root / "requirements.txt").write_text(content, encoding="utf-8")

    def _create_gitignore(self, root: Path):
        content = "__pycache__/\n*.pyc\n.env\n.venv/\n.vscode/\n"
        (root / ".gitignore").write_text(content, encoding="utf-8")

    def _create_microservice_boilerplate(self, root: Path, name: str):
        # Create a standard microservice file
        content = f'''"""
SERVICE_NAME: _{name}MS
ENTRY_POINT: _{name}MS.py
DEPENDENCIES: None
"""
from typing import Dict, Any, Optional
from microservice_std_lib import service_metadata, service_endpoint

@service_metadata(
    name="{name}",
    version="1.0.0",
    description="Auto-generated microservice.",
    tags=["new"],
    capabilities=[]
)
class {name}MS:
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {{}}

    @service_endpoint(
        inputs={{}},
        outputs={{"message": "str"}},
        description="Default endpoint.",
        tags=["hello"]
    )
    def hello(self):
        return {{"message": "Hello from {name}!"}}

if __name__ == "__main__":
    svc = {name}MS()
    print("Service ready:", svc)
'''
        (root / "src" / f"_{name}MS.py").write_text(content, encoding="utf-8")

    def _create_standard_app_boilerplate(self, root: Path):
        content = "def main():\n    print('Hello World')\n\nif __name__ == '__main__':\n    main()"
        (root / "src" / "app.py").write_text(content, encoding="utf-8")

if __name__ == "__main__":
    forge = ProjectForgeMS()
    # Test creating a dummy project
    try:
        forge.forge_project(".", "TestForgedApp", ["pandas", "numpy"])
        print("Test Project Created.")
        shutil.rmtree("TestForgedApp") # Cleanup
        print("Test Project Cleaned up.")
    except Exception as e:
        print(f"Test failed: {e}")
