"""
SERVICE_NAME: _ProjectForgeMS
ENTRY_POINT: _ProjectForgeMS.py
INTERNAL_DEPENDENCIES: microservice_std_lib
EXTERNAL_DEPENDENCIES: None
"""
import os
import shutil
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional
from microservice_std_lib import service_metadata, service_endpoint
logger = logging.getLogger('ProjectForge')

@service_metadata(name='ProjectForge', version='1.0.0', description='Scaffolding engine for creating new microservice projects or Python apps.', tags=['scaffolding', 'generator', 'filesystem'], capabilities=['filesystem:write'], internal_dependencies=['microservice_std_lib'], external_dependencies=[])
class ProjectForgeMS:
    """
    The Blacksmith.
    Creates directory structures, stamps out boilerplate code, and injects dependencies.
    """

    def __init__(self, config: Optional[Dict[str, Any]]=None):
        self.config = config or {}
        self.template_root = self.config.get('template_root')

    @service_endpoint(inputs={'parent_path': 'str', 'project_name': 'str', 'dependencies': 'List[str]', 'type': 'str'}, outputs={'path': 'str', 'status': 'str'}, description='Creates a new standardized Python project with the given specifications.', tags=['create', 'scaffold'], side_effects=['filesystem:write'])
    def forge_project(self, parent_path: str, project_name: str, dependencies: List[str]=None, project_type: str='microservice') -> Dict[str, Any]:
        """
        Stamps out a new project folder.
        """
        root = Path(parent_path).resolve()
        project_dir = root / project_name
        if project_dir.exists():
            raise FileExistsError(f'Directory already exists: {project_dir}')
        logger.info(f"Forging new project '{project_name}' at {project_dir}...")
        try:
            project_dir.mkdir(parents=True)
            (project_dir / 'src').mkdir()
            (project_dir / 'tests').mkdir()
            (project_dir / 'config').mkdir()
            self._create_readme(project_dir, project_name)
            self._create_requirements(project_dir, dependencies or [])
            self._create_gitignore(project_dir)
            if project_type == 'microservice':
                self._create_microservice_boilerplate(project_dir, project_name)
            else:
                self._create_standard_app_boilerplate(project_dir)
            return {'path': str(project_dir), 'status': 'created', 'name': project_name}
        except Exception as e:
            logger.error(f'Forge failed: {e}')
            raise e

    def _create_readme(self, root: Path, name: str):
        content = f'# {name}\n\nGenerated by ProjectForgeMS.\n\n## Overview\nTODO: Add description.\n'
        (root / 'README.md').write_text(content, encoding='utf-8')

    def _create_requirements(self, root: Path, deps: List[str]):
        base_deps = ['requests', 'logging']
        all_deps = sorted(list(set(base_deps + deps)))
        content = '\n'.join(all_deps)
        (root / 'requirements.txt').write_text(content, encoding='utf-8')

    def _create_gitignore(self, root: Path):
        content = '__pycache__/\n*.pyc\n.env\n.venv/\n.vscode/\n'
        (root / '.gitignore').write_text(content, encoding='utf-8')

    def _create_microservice_boilerplate(self, root: Path, name: str):
        content = f'"""\nSERVICE_NAME: _{name}MS\nENTRY_POINT: _{name}MS.py\nDEPENDENCIES: None\n"""\nfrom typing import Dict, Any, Optional\nfrom microservice_std_lib import service_metadata, service_endpoint\n\n@service_metadata(\n    name="{name}",\n    version="1.0.0",\n    description="Auto-generated microservice.",\n    tags=["new"],\n    capabilities=[]\n)\nclass {name}MS:\n    def __init__(self, config: Optional[Dict[str, Any]] = None):\n        self.config = config or {{}}\n\n    @service_endpoint(\n        inputs={{}},\n        outputs={{"message": "str"}},\n        description="Default endpoint.",\n        tags=["hello"]\n    )\n    def hello(self):\n        return {{"message": "Hello from {name}!"}}\n\nif __name__ == "__main__":\n    svc = {name}MS()\n    print("Service ready:", svc)\n'
        (root / 'src' / f'_{name}MS.py').write_text(content, encoding='utf-8')

    def _create_standard_app_boilerplate(self, root: Path):
        content = "def main():\n    print('Hello World')\n\nif __name__ == '__main__':\n    main()"
        (root / 'src' / 'app.py').write_text(content, encoding='utf-8')
if __name__ == '__main__':
    forge = ProjectForgeMS()
    try:
        forge.forge_project('.', 'TestForgedApp', ['pandas', 'numpy'])
        print('Test Project Created.')
        shutil.rmtree('TestForgedApp')
        print('Test Project Cleaned up.')
    except Exception as e:
        print(f'Test failed: {e}')
